apiVersion: v1
kind: Service
metadata:
  name: transaction-api
  namespace: fintech-system
  labels:
    app: transaction-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: transaction-api