apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-service-account
  namespace: fintech-system
  labels:
    app: fintech-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fintech-role
  namespace: fintech-system
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fintech-role-binding
  namespace: fintech-system
subjects:
  - kind: ServiceAccount
    name: fintech-service-account
    namespace: fintech-system
roleRef:
  kind: Role
  name: fintech-role
  apiGroup: rbac.authorization.k8s.io