apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: fintech-system
data:
  NODE_ENV: "production"
  PORT: "8081"
  DB_NAME: "fintech"
  DB_USER: "postgres"
  DB_PORT: "5432"